q_ww_lowerLimit
q_ww_upperLimit
q_ww_flowSum

q_ww_balance

q_ww_flagTransfer1
q_ww_flagTransfer2
q_ww_flagTransfer3
q_ww_flagState1
q_ww_flagState2
q_ww_flagState3

//q_ww_transferShareInfluent
//q_ww_transferShareEffluent
//q_ww_spillstate
//q_ww_transferstate