# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../titan/ui/input_verifier_form.ui'
#
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(550, 672)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_project_dir = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_project_dir.setFont(font)
        self.label_project_dir.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_project_dir.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_project_dir.setLineWidth(2)
        self.label_project_dir.setAlignment(QtCore.Qt.AlignCenter)
        self.label_project_dir.setObjectName("label_project_dir")
        self.verticalLayout.addWidget(self.label_project_dir)
        self.treeView_setuptree = QtWidgets.QTreeView(Form)
        self.treeView_setuptree.setFrameShape(QtWidgets.QFrame.Box)
        self.treeView_setuptree.setFrameShadow(QtWidgets.QFrame.Plain)
        self.treeView_setuptree.setLineWidth(1)
        self.treeView_setuptree.setObjectName("treeView_setuptree")
        self.verticalLayout.addWidget(self.treeView_setuptree)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setLineWidth(2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listView_required_files = QtWidgets.QListView(Form)
        self.listView_required_files.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listView_required_files.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.listView_required_files.setFrameShape(QtWidgets.QFrame.Box)
        self.listView_required_files.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listView_required_files.setLineWidth(1)
        self.listView_required_files.setObjectName("listView_required_files")
        self.verticalLayout.addWidget(self.listView_required_files)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setLineWidth(2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textBrowser_output = QtWidgets.QTextBrowser(Form)
        self.textBrowser_output.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textBrowser_output.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.textBrowser_output.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser_output.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_output.setLineWidth(1)
        self.textBrowser_output.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textBrowser_output.setOpenLinks(False)
        self.textBrowser_output.setObjectName("textBrowser_output")
        self.verticalLayout.addWidget(self.textBrowser_output)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_close = QtWidgets.QPushButton(Form)
        self.pushButton_close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_close.setDefault(True)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout.addWidget(self.pushButton_close)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Verify Input"))
        self.label_project_dir.setText(_translate("Form", "Project Directory"))
        self.label.setText(_translate("Form", "Required Input Files"))
        self.label_2.setText(_translate("Form", "Details"))
        self.pushButton_close.setText(_translate("Form", "Close"))

