# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../titan/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1106, 728)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 80, 361, 601))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeView_setups = QtWidgets.QTreeView(self.horizontalLayoutWidget)
        self.treeView_setups.setObjectName("treeView_setups")
        self.horizontalLayout.addWidget(self.treeView_setups)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.listView_tools = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_tools.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listView_tools.setObjectName("listView_tools")
        self.verticalLayout_2.addWidget(self.listView_tools)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.listView_dataformats_input = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_dataformats_input.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listView_dataformats_input.setObjectName("listView_dataformats_input")
        self.verticalLayout_2.addWidget(self.listView_dataformats_input)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.listView_dataformats_output = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_dataformats_output.setObjectName("listView_dataformats_output")
        self.verticalLayout_2.addWidget(self.listView_dataformats_output)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.checkBox_debug = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_debug.setGeometry(QtCore.QRect(1030, 0, 61, 17))
        self.checkBox_debug.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_debug.setChecked(True)
        self.checkBox_debug.setObjectName("checkBox_debug")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(240, 10, 641, 49))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.horizontalLayoutWidget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_create_test_setups = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_create_test_setups.setObjectName("pushButton_create_test_setups")
        self.gridLayout.addWidget(self.pushButton_create_test_setups, 0, 0, 1, 1)
        self.pushButton_create_setups_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_create_setups_3.setObjectName("pushButton_create_setups_3")
        self.gridLayout.addWidget(self.pushButton_create_setups_3, 0, 3, 1, 1)
        self.pushButton_create_setups_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_create_setups_1.setObjectName("pushButton_create_setups_1")
        self.gridLayout.addWidget(self.pushButton_create_setups_1, 0, 1, 1, 1)
        self.pushButton_create_setups_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_create_setups_2.setObjectName("pushButton_create_setups_2")
        self.gridLayout.addWidget(self.pushButton_create_setups_2, 0, 2, 1, 1)
        self.pushButton_execute = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_execute.setGeometry(QtCore.QRect(50, 40, 75, 23))
        self.pushButton_execute.setObjectName("pushButton_execute")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(130, 40, 75, 23))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_test = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_test.setGeometry(QtCore.QRect(90, 10, 75, 23))
        self.pushButton_test.setObjectName("pushButton_test")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(370, 79, 721, 601))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textBrowser_main = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_main.setMinimumSize(QtCore.QSize(719, 0))
        self.textBrowser_main.setObjectName("textBrowser_main")
        self.verticalLayout.addWidget(self.textBrowser_main)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textBrowser_process_output = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_process_output.setMinimumSize(QtCore.QSize(719, 0))
        self.textBrowser_process_output.setObjectName("textBrowser_process_output")
        self.verticalLayout.addWidget(self.textBrowser_process_output)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1106, 21))
        self.menubar.setObjectName("menubar")
        self.menuSceleton_Titan = QtWidgets.QMenu(self.menubar)
        self.menuSceleton_Titan.setObjectName("menuSceleton_Titan")
        self.menuProject = QtWidgets.QMenu(self.menuSceleton_Titan)
        self.menuProject.setObjectName("menuProject")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.actionSave_Project = QtWidgets.QAction(MainWindow)
        self.actionSave_Project.setObjectName("actionSave_Project")
        self.actionLoad_Project = QtWidgets.QAction(MainWindow)
        self.actionLoad_Project.setObjectName("actionLoad_Project")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuProject.addAction(self.actionSave)
        self.menuProject.addAction(self.actionLoad)
        self.menuProject.addAction(self.actionNew)
        self.menuSceleton_Titan.addAction(self.menuProject.menuAction())
        self.menuSceleton_Titan.addSeparator()
        self.menuSceleton_Titan.addAction(self.action_quit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuSceleton_Titan.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sceleton Titan"))
        self.label_3.setText(_translate("MainWindow", "Tool"))
        self.label_4.setText(_translate("MainWindow", "Input formats"))
        self.label_5.setText(_translate("MainWindow", "Output formats"))
        self.checkBox_debug.setText(_translate("MainWindow", "Debug"))
        self.pushButton_create_test_setups.setText(_translate("MainWindow", "Test Setups"))
        self.pushButton_create_setups_3.setText(_translate("MainWindow", "Setups\n"
"\'invest\' -> \'MIP\' and\n"
"\'invest\' -> \'LP\'"))
        self.pushButton_create_setups_1.setText(_translate("MainWindow", "Setups \n"
" \'base\' -> \'setup A\'"))
        self.pushButton_create_setups_2.setText(_translate("MainWindow", "Setups\n"
"\'invest -> \'MIP\'"))
        self.pushButton_execute.setText(_translate("MainWindow", "Execute"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_test.setText(_translate("MainWindow", "Test"))
        self.label.setText(_translate("MainWindow", "Titan Output"))
        self.label_2.setText(_translate("MainWindow", "GAMS Output"))
        self.menuSceleton_Titan.setTitle(_translate("MainWindow", "File"))
        self.menuProject.setTitle(_translate("MainWindow", "Project..."))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.action_quit.setText(_translate("MainWindow", "Exit"))
        self.actionSave_Project.setText(_translate("MainWindow", "Save"))
        self.actionLoad_Project.setText(_translate("MainWindow", "Load"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))

