# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../titan/ui/settings.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsForm(object):
    def setupUi(self, SettingsForm):
        SettingsForm.setObjectName("SettingsForm")
        SettingsForm.setWindowModality(QtCore.Qt.ApplicationModal)
        SettingsForm.resize(700, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsForm.sizePolicy().hasHeightForWidth())
        SettingsForm.setSizePolicy(sizePolicy)
        SettingsForm.setMinimumSize(QtCore.QSize(700, 500))
        SettingsForm.setMaximumSize(QtCore.QSize(700, 500))
        SettingsForm.setMouseTracking(False)
        SettingsForm.setFocusPolicy(QtCore.Qt.StrongFocus)
        SettingsForm.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        SettingsForm.setAutoFillBackground(False)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(SettingsForm)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_general = QtWidgets.QGroupBox(SettingsForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_general.sizePolicy().hasHeightForWidth())
        self.groupBox_general.setSizePolicy(sizePolicy)
        self.groupBox_general.setMinimumSize(QtCore.QSize(0, 164))
        self.groupBox_general.setAutoFillBackground(False)
        self.groupBox_general.setFlat(False)
        self.groupBox_general.setObjectName("groupBox_general")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_general)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox_exit_dialog = QtWidgets.QCheckBox(self.groupBox_general)
        self.checkBox_exit_dialog.setTristate(False)
        self.checkBox_exit_dialog.setObjectName("checkBox_exit_dialog")
        self.verticalLayout_6.addWidget(self.checkBox_exit_dialog)
        self.checkBox_save_at_exit = QtWidgets.QCheckBox(self.groupBox_general)
        self.checkBox_save_at_exit.setTristate(True)
        self.checkBox_save_at_exit.setObjectName("checkBox_save_at_exit")
        self.verticalLayout_6.addWidget(self.checkBox_save_at_exit)
        self.checkBox_del_work_dirs = QtWidgets.QCheckBox(self.groupBox_general)
        self.checkBox_del_work_dirs.setTristate(True)
        self.checkBox_del_work_dirs.setObjectName("checkBox_del_work_dirs")
        self.verticalLayout_6.addWidget(self.checkBox_del_work_dirs)
        self.checkBox_debug = QtWidgets.QCheckBox(self.groupBox_general)
        self.checkBox_debug.setObjectName("checkBox_debug")
        self.verticalLayout_6.addWidget(self.checkBox_debug)
        self.label_4 = QtWidgets.QLabel(self.groupBox_general)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_project_dir_location = QtWidgets.QLineEdit(self.groupBox_general)
        self.lineEdit_project_dir_location.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_project_dir_location.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_project_dir_location.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_project_dir_location.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_project_dir_location.setFrame(False)
        self.lineEdit_project_dir_location.setClearButtonEnabled(True)
        self.lineEdit_project_dir_location.setObjectName("lineEdit_project_dir_location")
        self.horizontalLayout_3.addWidget(self.lineEdit_project_dir_location)
        self.pushButton_browse_project_dir = QtWidgets.QPushButton(self.groupBox_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_browse_project_dir.sizePolicy().hasHeightForWidth())
        self.pushButton_browse_project_dir.setSizePolicy(sizePolicy)
        self.pushButton_browse_project_dir.setMinimumSize(QtCore.QSize(55, 20))
        self.pushButton_browse_project_dir.setMaximumSize(QtCore.QSize(55, 20))
        self.pushButton_browse_project_dir.setObjectName("pushButton_browse_project_dir")
        self.horizontalLayout_3.addWidget(self.pushButton_browse_project_dir)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_general)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox_setup = QtWidgets.QGroupBox(SettingsForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_setup.sizePolicy().hasHeightForWidth())
        self.groupBox_setup.setSizePolicy(sizePolicy)
        self.groupBox_setup.setMaximumSize(QtCore.QSize(16777215, 121))
        self.groupBox_setup.setObjectName("groupBox_setup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_setup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_clear_flags = QtWidgets.QCheckBox(self.groupBox_setup)
        self.checkBox_clear_flags.setObjectName("checkBox_clear_flags")
        self.verticalLayout_2.addWidget(self.checkBox_clear_flags)
        self.checkBox_del_input_dirs = QtWidgets.QCheckBox(self.groupBox_setup)
        self.checkBox_del_input_dirs.setObjectName("checkBox_del_input_dirs")
        self.verticalLayout_2.addWidget(self.checkBox_del_input_dirs)
        self.verticalLayout.addWidget(self.groupBox_setup)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.groupBox_gams = QtWidgets.QGroupBox(SettingsForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_gams.sizePolicy().hasHeightForWidth())
        self.groupBox_gams.setSizePolicy(sizePolicy)
        self.groupBox_gams.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_gams.setFlat(False)
        self.groupBox_gams.setCheckable(False)
        self.groupBox_gams.setObjectName("groupBox_gams")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_gams)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox_logoption = QtWidgets.QCheckBox(self.groupBox_gams)
        self.checkBox_logoption.setObjectName("checkBox_logoption")
        self.verticalLayout_5.addWidget(self.checkBox_logoption)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox_gams)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.spinBox_cerr = QtWidgets.QSpinBox(self.groupBox_gams)
        self.spinBox_cerr.setMaximumSize(QtCore.QSize(40, 16777215))
        self.spinBox_cerr.setFrame(True)
        self.spinBox_cerr.setProperty("showGroupSeparator", False)
        self.spinBox_cerr.setProperty("value", 1)
        self.spinBox_cerr.setObjectName("spinBox_cerr")
        self.horizontalLayout_4.addWidget(self.spinBox_cerr)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox_gams)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_gamside_path = QtWidgets.QLineEdit(self.groupBox_gams)
        self.lineEdit_gamside_path.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_gamside_path.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_gamside_path.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_gamside_path.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_gamside_path.setAutoFillBackground(False)
        self.lineEdit_gamside_path.setFrame(False)
        self.lineEdit_gamside_path.setReadOnly(False)
        self.lineEdit_gamside_path.setClearButtonEnabled(True)
        self.lineEdit_gamside_path.setObjectName("lineEdit_gamside_path")
        self.horizontalLayout_5.addWidget(self.lineEdit_gamside_path)
        self.pushButton_browse_gamside = QtWidgets.QPushButton(self.groupBox_gams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_browse_gamside.sizePolicy().hasHeightForWidth())
        self.pushButton_browse_gamside.setSizePolicy(sizePolicy)
        self.pushButton_browse_gamside.setMinimumSize(QtCore.QSize(55, 20))
        self.pushButton_browse_gamside.setMaximumSize(QtCore.QSize(55, 20))
        self.pushButton_browse_gamside.setObjectName("pushButton_browse_gamside")
        self.horizontalLayout_5.addWidget(self.pushButton_browse_gamside)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.groupBox_gams)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_project = QtWidgets.QGroupBox(SettingsForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_project.sizePolicy().hasHeightForWidth())
        self.groupBox_project.setSizePolicy(sizePolicy)
        self.groupBox_project.setMinimumSize(QtCore.QSize(250, 300))
        self.groupBox_project.setObjectName("groupBox_project")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_project)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_project)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.lineEdit_project_name = QtWidgets.QLineEdit(self.groupBox_project)
        self.lineEdit_project_name.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_project_name.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_project_name.setStyleSheet("color: \'black\'")
        self.lineEdit_project_name.setReadOnly(True)
        self.lineEdit_project_name.setObjectName("lineEdit_project_name")
        self.verticalLayout_4.addWidget(self.lineEdit_project_name)
        self.label_3 = QtWidgets.QLabel(self.groupBox_project)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.textEdit_project_description = QtWidgets.QTextEdit(self.groupBox_project)
        self.textEdit_project_description.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_project_description.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textEdit_project_description.setStyleSheet(":focus {border: 1px solid black;}")
        self.textEdit_project_description.setTabChangesFocus(True)
        self.textEdit_project_description.setReadOnly(False)
        self.textEdit_project_description.setAcceptRichText(False)
        self.textEdit_project_description.setPlaceholderText("")
        self.textEdit_project_description.setObjectName("textEdit_project_description")
        self.verticalLayout_4.addWidget(self.textEdit_project_description)
        self.label_6 = QtWidgets.QLabel(self.groupBox_project)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_work_dir_location = QtWidgets.QLineEdit(self.groupBox_project)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_work_dir_location.sizePolicy().hasHeightForWidth())
        self.lineEdit_work_dir_location.setSizePolicy(sizePolicy)
        self.lineEdit_work_dir_location.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_work_dir_location.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_work_dir_location.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_work_dir_location.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_work_dir_location.setFrame(False)
        self.lineEdit_work_dir_location.setClearButtonEnabled(True)
        self.lineEdit_work_dir_location.setObjectName("lineEdit_work_dir_location")
        self.horizontalLayout_6.addWidget(self.lineEdit_work_dir_location)
        self.pushButton_browse_work_dir = QtWidgets.QPushButton(self.groupBox_project)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_browse_work_dir.sizePolicy().hasHeightForWidth())
        self.pushButton_browse_work_dir.setSizePolicy(sizePolicy)
        self.pushButton_browse_work_dir.setMinimumSize(QtCore.QSize(55, 20))
        self.pushButton_browse_work_dir.setMaximumSize(QtCore.QSize(55, 20))
        self.pushButton_browse_work_dir.setObjectName("pushButton_browse_work_dir")
        self.horizontalLayout_6.addWidget(self.pushButton_browse_work_dir)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addWidget(self.groupBox_project)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 6, -1, 6)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_ok = QtWidgets.QPushButton(SettingsForm)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton_cancel = QtWidgets.QPushButton(SettingsForm)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_statusbar_placeholder = QtWidgets.QHBoxLayout()
        self.horizontalLayout_statusbar_placeholder.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_statusbar_placeholder.setSpacing(0)
        self.horizontalLayout_statusbar_placeholder.setObjectName("horizontalLayout_statusbar_placeholder")
        self.widget_invisible_dummy = QtWidgets.QWidget(SettingsForm)
        self.widget_invisible_dummy.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_invisible_dummy.setMaximumSize(QtCore.QSize(0, 20))
        self.widget_invisible_dummy.setObjectName("widget_invisible_dummy")
        self.horizontalLayout_statusbar_placeholder.addWidget(self.widget_invisible_dummy)
        self.verticalLayout_7.addLayout(self.horizontalLayout_statusbar_placeholder)

        self.retranslateUi(SettingsForm)
        QtCore.QMetaObject.connectSlotsByName(SettingsForm)
        SettingsForm.setTabOrder(self.checkBox_exit_dialog, self.checkBox_save_at_exit)
        SettingsForm.setTabOrder(self.checkBox_save_at_exit, self.checkBox_del_work_dirs)
        SettingsForm.setTabOrder(self.checkBox_del_work_dirs, self.checkBox_debug)
        SettingsForm.setTabOrder(self.checkBox_debug, self.pushButton_browse_project_dir)
        SettingsForm.setTabOrder(self.pushButton_browse_project_dir, self.checkBox_clear_flags)
        SettingsForm.setTabOrder(self.checkBox_clear_flags, self.checkBox_del_input_dirs)
        SettingsForm.setTabOrder(self.checkBox_del_input_dirs, self.checkBox_logoption)
        SettingsForm.setTabOrder(self.checkBox_logoption, self.spinBox_cerr)
        SettingsForm.setTabOrder(self.spinBox_cerr, self.pushButton_browse_gamside)
        SettingsForm.setTabOrder(self.pushButton_browse_gamside, self.textEdit_project_description)
        SettingsForm.setTabOrder(self.textEdit_project_description, self.pushButton_browse_work_dir)
        SettingsForm.setTabOrder(self.pushButton_browse_work_dir, self.pushButton_ok)
        SettingsForm.setTabOrder(self.pushButton_ok, self.pushButton_cancel)

    def retranslateUi(self, SettingsForm):
        _translate = QtCore.QCoreApplication.translate
        SettingsForm.setWindowTitle(_translate("SettingsForm", "Settings"))
        self.groupBox_general.setTitle(_translate("SettingsForm", "General"))
        self.checkBox_exit_dialog.setToolTip(_translate("SettingsForm", "<html><head/><body><p>Unchecked: Exit Sceleton without prompt</p><p>Checked: Show confirm exit prompt</p><p><br/></p></body></html>"))
        self.checkBox_exit_dialog.setText(_translate("SettingsForm", "Show confirm exit dialog at exit"))
        self.checkBox_save_at_exit.setToolTip(_translate("SettingsForm", "<html><head/><body><p>Unchecked: Does not save project &amp; does not show message box</p><p>Partially checked: Shows message box (default)</p><p>Checked: Saves project &amp; does not show message box</p><p><br/></p></body></html>"))
        self.checkBox_save_at_exit.setText(_translate("SettingsForm", "Save changes to project at exit"))
        self.checkBox_del_work_dirs.setToolTip(_translate("SettingsForm", "<html><head/><body><p>Unchecked: Does not delete work directories &amp; does not show message box</p><p>Partially checked: Shows message box (default)</p><p>Checked: Deletes work directories &amp; does not show message box</p><p><br/></p></body></html>"))
        self.checkBox_del_work_dirs.setText(_translate("SettingsForm", "Delete work directories at exit"))
        self.checkBox_debug.setToolTip(_translate("SettingsForm", "<html><head/><body><p>Shows Sceleton debug messages in console. Error messages are always shown.</p></body></html>"))
        self.checkBox_debug.setText(_translate("SettingsForm", "Show Debug messages"))
        self.label_4.setText(_translate("SettingsForm", "Projects directory"))
        self.lineEdit_project_dir_location.setToolTip(_translate("SettingsForm", "<html><head/><body><p>Path to Sceleton projects. I.e. Directory for saving &amp; loading projects.</p></body></html>"))
        self.lineEdit_project_dir_location.setPlaceholderText(_translate("SettingsForm", "Using default directory"))
        self.pushButton_browse_project_dir.setToolTip(_translate("SettingsForm", "<html><head/><body><p>Select projects directory</p></body></html>"))
        self.pushButton_browse_project_dir.setText(_translate("SettingsForm", "Browse"))
        self.groupBox_setup.setTitle(_translate("SettingsForm", "Setup"))
        self.checkBox_clear_flags.setToolTip(_translate("SettingsForm", "<html><head/><body><p>Clear Setup <span style=\" font-weight:600;\">ready</span> and <span style=\" font-weight:600;\">failed</span> flags at startup and when a project is loaded</p></body></html>"))
        self.checkBox_clear_flags.setText(_translate("SettingsForm", "Clear Setup flags at startup"))
        self.checkBox_del_input_dirs.setToolTip(_translate("SettingsForm", "<html><head/><body><p>Check this box to delete input directory when deleting a Setup. Deletes children\'s input directories as well.</p></body></html>"))
        self.checkBox_del_input_dirs.setText(_translate("SettingsForm", "Delete input directory when Setup is deleted"))
        self.groupBox_gams.setTitle(_translate("SettingsForm", "GAMS"))
        self.checkBox_logoption.setToolTip(_translate("SettingsForm", "<html><head/><body><p>Controls the GAMS <span style=\" font-weight:600;\">logoption</span> keyword value.</p><p>If unchecked (logoption=3). LOG output is written to standard output. </p><p>If checked (logoption=4). LOG output is written to standard output and to &lt;TOOLNAME&gt;.log file.</p></body></html>"))
        self.checkBox_logoption.setText(_translate("SettingsForm", "Write output to log file (logoption)"))
        self.label.setToolTip(_translate("SettingsForm", "<html><head/><body><p>Controls the compile time error limit (<span style=\" font-weight:600;\">cerr</span>). The compilation will be stopped after n errors have occurred.</p><p>0: No error limit (default)</p><p>n: Stop after n errors</p></body></html>"))
        self.label.setText(_translate("SettingsForm", "Compile error limit (cerr)"))
        self.spinBox_cerr.setToolTip(_translate("SettingsForm", "<html><head/><body><p>Controls the compile time error limit (<span style=\" font-weight:600;\">cerr</span>). The compilation will be stopped after n errors have occurred.</p><p>0: No error limit (default)</p><p>n: Stop after n errors</p></body></html>"))
        self.label_5.setText(_translate("SettingsForm", "GAMS directory"))
        self.lineEdit_gamside_path.setToolTip(_translate("SettingsForm", "<html><head/><body><p>Enter directory where gams.exe and gamside.exe reside.</p><p>Note: Leave this empty to use GAMS defined in the system PATH variable.</p></body></html>"))
        self.lineEdit_gamside_path.setPlaceholderText(_translate("SettingsForm", "Using system path GAMS"))
        self.pushButton_browse_gamside.setToolTip(_translate("SettingsForm", "<html><head/><body><p>Select GAMS directory</p></body></html>"))
        self.pushButton_browse_gamside.setText(_translate("SettingsForm", "Browse"))
        self.groupBox_project.setTitle(_translate("SettingsForm", "Project"))
        self.label_2.setText(_translate("SettingsForm", "Name"))
        self.lineEdit_project_name.setPlaceholderText(_translate("SettingsForm", "No project open"))
        self.label_3.setText(_translate("SettingsForm", "Description"))
        self.label_6.setText(_translate("SettingsForm", "Work directory"))
        self.lineEdit_work_dir_location.setToolTip(_translate("SettingsForm", "<html><head/><body><p>Work directory location. Leave this empty to use default.</p></body></html>"))
        self.lineEdit_work_dir_location.setPlaceholderText(_translate("SettingsForm", "Using default directory"))
        self.pushButton_browse_work_dir.setToolTip(_translate("SettingsForm", "<html><head/><body><p>Select work directory</p></body></html>"))
        self.pushButton_browse_work_dir.setText(_translate("SettingsForm", "Browse"))
        self.pushButton_ok.setToolTip(_translate("SettingsForm", "<html><head/><body><p>Saves changes and closes the window</p></body></html>"))
        self.pushButton_ok.setText(_translate("SettingsForm", "Ok"))
        self.pushButton_cancel.setToolTip(_translate("SettingsForm", "<html><head/><body><p>Closes the window without saving changes</p></body></html>"))
        self.pushButton_cancel.setText(_translate("SettingsForm", "Cancel"))

