#!/bin/sh
#
# A hook script to write the version info.
#
# To enable this hook, copy this file to ".git/hooks/".
#

git describe --dirty=+ --always > version_git
set /p commit= < version_git
del version_git 
echo 'version' %commit% > version_git